server:
  port: 8080
spring:
  datasource:
#    url: jdbc:postgresql://db:5432/compose-postgres
#    driver-class-name: org.postgresql.Driver
#    username: docker-compose
#    password: docker-compose
    url: jdbc:postgresql://localhost:5477/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      jpa:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        use_sql_comments: true
        format_sql: true

  main:
    allow-bean-definition-overriding: true
#  sql:
#    init:
#      data-locations: init.sql
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#=======================================================
# Swagger
# http://localhost:8080/api/swagger-ui/index.html
#=======================================================

springfox:
  documentation:
    swagger-ui:
      base-url: /api
      enabled: true