### If you run Application.java, befor strat run 'init.sql' script in test resources in order to generate Bank and Addresses in DB.

### If you use docker compose then port 8000
### If you use Application.java then port 8080


### Create first user
PUT http://localhost:8000/user/create
Content-Type: application/json

{
  "bankId": 1,
  "contactInformation": {
    "address": "Exchange line, 4",
    "city": "Saint-Petersburg",
    "country": "Russia",
    "email": "kirill@gmail.com",
    "phoneNumber": "+79213463434"
  },
  "firstName": "Kirill",
  "lastName": "Pavlovich",
  "status": "enabled"
}

### Create second user
PUT http://localhost:8000/user/create
Content-Type: application/json

{
"bankId": 2,
"contactInformation": {
"address": "Exchange line, 5",
"city": "Saint-Petersburg",
"country": "Russia",
"email": "vadim@gmail.com",
"phoneNumber": "+7921346634"
},
"firstName": "Vadim",
"lastName": "Vadimovich",
"status": "enabled"
}

### create account (ctreate first account and then second)
POST http://localhost:8000/account/create
Content-Type: application/json

{
  "accountBalance": 10000,
  "accountStatus": "enable",
  "accountType": "dollars",
  "userNumber": 1
}

### do transaction +plus balance on account number from user
POST http://localhost:8000/transaction/toUp
Content-Type: application/json

{
  "accountNumber": 2,
  "txAmount": 1200,
  "txType": "toUp"
}

### do transaction -minus balance on account number from user
POST http://localhost:8000/transaction/withdraw
Content-Type: application/json

{
  "accountNumber": 1,
  "txAmount": 200,
  "txType": "withdraw"
}

### do transfer transaction from one user to another on account numbers
POST http://localhost:8000/transaction/transfer
Content-Type: application/json

{
  "accountNumber": 1,
  "toAccountNumber": 2,
  "txAmount": 200,
  "txType": "transfer"
}

### get user on account number (id)
GET http://localhost:8000/user/1
Content-Type: application/json

### get all users
GET http://localhost:8000/user/all
Content-Type: application/json

### delete user on id
DELETE http://localhost:8000/user/delete/1
Content-Type: application/json
